### PR TITLE
Bump Vue.js version to v3

### PR DESCRIPTION
**Pull request by creynir**
Just a small update to the Vue3 / next version.

### CODE REVIEW

**Review by AviVahl — APPROVED** [review]

**Comment by AviVahl** [comment]
Awesome contribution. Thanks!
I've updated the lock file to refer to the official public registry (or at least yarn's proxy to it), as this project is open source.

**Comment by creynir** [comment]
Thanks for catching it, totally forgot I had private registry set up )

**Comment by AviVahl** [comment]
You may also want to link future commits with your GitHub account. Probably need to make sure git has an email address configured (matching the one set in GitHub).

**Comment by creynir** [comment]
Yes, it was merged at the time I thought about it. 
Btw I tried to put stylable styles in <style> tag but webpack loader was throwing errors so I switched back to plugin. In general it’s more common for vue developer to have styles inside vue component.

**Pull request merged**
